spring:
    datasource:
        url: jdbc:h2:mem:aragraph2024
        driver-class-name: org.h2.Driver
        username: aragraph
        password:
    jpa:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: create #Vai criar as tabelas automatico
      properties:
        hibernate:
          format_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
        
        
        
